excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: https://maikotrindade.com
title: Maiko Trindade
description: technology, Android, Jetpack Compose, Blockchain, ESG, Crypto, Solidity, Software Development, Linux, web and computer science

paginate: 5
paginate_path: "/blog/page:num/"
include:
  - ads.txt