excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://maikotrindade.com
title: Maiko Trindade
description: technology, Android, Jetpack Compose, Blockchain, Cryptocurrency, Crypto, Solidity, Software Development, Linux, web, computer science, software development methodology and Open Source

paginate: 5
paginate_path: "/blog/page:num/"